.github/workflows/workflow.yml

* Triggers CI only on pull_requests and pushes to master branch.
* Explicitly sets GA runner macOS version to 10.15 (`jpackage` fails on `latest` macOS runner).
Closes #2 .

Update CI branch triggers

---

.github/.codecov.yml

* Delays codecov result reporting until all 3 platform pipelines are done creating their respective coverage reports.
Closes #18 .

Delay CI codecov result notification

---

src/main/java/com/github/mfl28/boundingboxeditor/ui/ObjectTreeElementCell.java
src/test/java/com/github/mfl28/boundingboxeditor/ui/ObjectTreeTests.java

* Removes the "Change Category" contextmenu-item for object tree cells whose corresponding cell-object is not a `View` instance.
* Adds test assertions.
Fixes #22 .

Remove category change contextmenu item for non-View tree cells

---

build.gradle
src/main/java/com/github/mfl28/boundingboxeditor/model/io/restclients/BoundingBoxPredictionEntry.java
src/main/java/com/github/mfl28/boundingboxeditor/model/io/restclients/ModelEntry.java
src/test/java/com/github/mfl28/boundingboxeditor/model/io/ModelIoTests.java

* Explicitly add missing "uses" directives (that cannot be determined automatically) to jlink `mergeModule` section to fix modularity errors in the runtime images (-> jakarta).
* Transform `ModelEntry` and `BoundingBoxPredictionEntry` records back to data classes as  Gson does not seem to have reflective access to set the fields of records.
* Verify the equality contract of the data classes in unit tests.
Fixes #30 .

Fix reflection and modularity errors wrt. jakarta and gson.

---

src/main/java/com/github/mfl28/boundingboxeditor/ui/MainView.java
src/test/java/com/github/mfl28/boundingboxeditor/BoundingBoxEditorTestBase.java
src/test/java/com/github/mfl28/boundingboxeditor/ui/BoundingPolygonDrawingTests.java
src/test/java/com/github/mfl28/boundingboxeditor/ui/NoImageFolderOpenedBasicTests.java

* Adds feature that allows to drag and drop a folder (from outside the ap)p into the app and automatically load the images contained.
Closes #38 .

Add drag and drop image folder functionality

---

src/main/java/com/github/mfl28/boundingboxeditor/controller/Controller.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/BoundingBoxView.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/EditorImagePaneView.java

* Fixes bounding-box position updating when zooming/panning while constructing a new bounding-box.
* Drawing boxes and freehand-shapes now follows mouse-pointer while zooming/panning instead of jumping to new position when zooming/panning is finished.
Fixes #52 .

Fix drawing-zooming interaction

---

.github/.codecov.yml
src/main/java/com/github/mfl28/boundingboxeditor/ui/WorkspaceSplitPaneView.java

* Sets shape popover smallest side length to 25% of corresponding screen side length. This leads to more consistent popover sizes and improves popover-displaying of small shapes.
* Popover is no longer displayed for very small/empty shapes (where width/height ~0).
Closes #54 .

Improve shape tree cell popover displaying

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
gradlew
src/main/java/com/github/mfl28/boundingboxeditor/ui/ImageFileListView.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/MainView.java

* Upgrades to JavaFX 20.
* Upgrades Gradle version and dependencies.
* Adds explicit dependency of the Gradle `testCompileJava` task to `compileSass` task thereby removing a Gradle warning.
Closes #56 .

Upgrade JavaFX and dependencies

---

.github/workflows/workflow.yml

* Updates the used JDK version in Github Actions workflow to 17.0.8+7 (which should include fixes for macOS signing).
* Installer now works (tested on MacOS 13.4).
Closes #68 .

Update Github Actions Java version

---

src/main/java/com/github/mfl28/boundingboxeditor/ui/EditorImagePaneView.java

* Fixes division-by-zero case when computing scrolling `hvalue` and `vvalue`. This happens when the viewport and content pane sizes (doubles) are _exactly_ equal. This seems to happen frequently in Ubuntu (22).
* Note: Testfx does not seem to allow reproducing the issue via tests.
Fixes #70 .

Fix scrolling computation

---

src/main/java/com/github/mfl28/boundingboxeditor/BoundingBoxEditorApp.java
src/main/java/com/github/mfl28/boundingboxeditor/controller/Controller.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/MainView.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/ProgressViewer.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/ServiceProgressDialog.java
src/main/java/com/github/mfl28/boundingboxeditor/utils/UiUtils.java
src/test/java/com/github/mfl28/boundingboxeditor/ApplicationLaunchTest.java
src/test/java/com/github/mfl28/boundingboxeditor/BoundingBoxEditorTestBase.java

* Sets owners/parent windows for (application-modal) progress dialogs.
Closes #73 .

Set progress dialog owners

---

src/main/java/com/github/mfl28/boundingboxeditor/controller/Controller.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/EditorsSplitPaneView.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/ImageFileExplorerView.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/TagScrollPaneView.java

* Removes textfield focus when pressing enter.
Closes #75 .

Remove textfield focus when pressing enter

---

src/main/java/com/github/mfl28/boundingboxeditor/controller/Controller.java
src/main/java/com/github/mfl28/boundingboxeditor/controller/utils/KeyCombinationEventHandler.java
src/test/java/com/github/mfl28/boundingboxeditor/controller/SceneKeyShortcutTests.java
src/test/java/com/github/mfl28/boundingboxeditor/controller/utils/KeyCombinationEventHandlerTests.java

* Fixes handling of partial navigation  key-combination release. Images now load correctly even if only a part of the navigation key-combination is released.
* Updates and extends unit tests.
Fixes #77 .

Fix partial navigation key-combination release handling

---

src/main/java/com/github/mfl28/boundingboxeditor/controller/Controller.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/EditorToolBarView.java
src/main/resources/stylesheets/scss/styles.scss
src/test/java/com/github/mfl28/boundingboxeditor/controller/SceneKeyShortcutTests.java
src/test/java/com/github/mfl28/boundingboxeditor/ui/BoundingPolygonDrawingTests.java

* Makes drawing-mode selection toggle box more compact - removes text descriptions. Improves visual appearance.
* Sets more logical keyboard shortcuts for drawing-mode selection: `Ctrl+1/2/3`. 
* Updates unit tests.
Closes #79 .

Make drawing mode selection toggles more compact

---

.github/workflows/workflow.yml
build.gradle
src/main/java/com/github/mfl28/boundingboxeditor/controller/Controller.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/BoundingBoxView.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/BoundingPolygonView.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/EditorImagePaneView.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/TagScrollPaneView.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/settings/SettingsDialogView.java
src/test/java/com/github/mfl28/boundingboxeditor/controller/ControllerTests.java
src/test/java/com/github/mfl28/boundingboxeditor/controller/SceneKeyShortcutTests.java
src/test/java/com/github/mfl28/boundingboxeditor/ui/ImageFolderOpenedBasicTests.java

* Uses platform specific shortcut (Ctrl on Windows/Linux, Cmnd on Macos) everywhere.
* Updates unit tests to work on Macos.
* Upgrades to latest JavaFX version which fixes some errors on MacOS (e.g. exception when dragging multiple files into the program).
* Upgrades to latest testFX version.
Closes #94 .

Improve Macos shortcut handling

---

src/main/java/com/github/mfl28/boundingboxeditor/controller/Controller.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/BoundingBoxDrawer.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/BoundingFreeHandShapeDrawer.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/BoundingPolygonDrawer.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/BoundingShapeDrawer.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/EditorImagePaneView.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/EditorView.java
src/test/java/com/github/mfl28/boundingboxeditor/controller/SceneKeyShortcutTests.java
src/test/java/com/github/mfl28/boundingboxeditor/ui/BoundingPolygonDrawingTests.java

* Refactors bounding shape drawing using new `BoundingShapeDrawer` interface.
* Adds listeners that trigger bounding shape drawing finalization whenever the user clicks outside of the imageview or requests the program to exit.
* While drawing a polygon (after initial node click), all other existing bounding shapes in the scene are set to be mouse-transparent. This allows to draw polygons over other shapes. The mouse-transparency is reset when the drawn polygon is finalized.
* As with the other shapes, when drawing a polygon (by clicking to add nodes) keyboard-shortcuts are now ignored until the polygon is finalized.
* Updates and extends unit tests.
Closes #102 .

Refactor bounding shape drawing

---

src/main/java/com/github/mfl28/boundingboxeditor/model/io/services/ImageMetaDataLoadingService.java
src/test/java/com/github/mfl28/boundingboxeditor/ui/BoundingBoxDrawingTests.java

* Ignores files with known annotation extension (`.txt`, `.data`, `.xml`, `.json`) when loading images from a folder. The program will no longer show "Invalid image file." errors if files with these extensions are present in an image folder.
* Adds and updates test files.
Closes #67.

Ignore files with known annotation extension when loading images

---

src/main/java/com/github/mfl28/boundingboxeditor/controller/Controller.java
src/test/java/com/github/mfl28/boundingboxeditor/controller/SceneKeyShortcutTests.java

* Adds `Ctrl/Cmnd+,` shortcut to open settings.
Closes #105.

Add open settings keyboard shortcut

---

src/main/java/com/github/mfl28/boundingboxeditor/controller/Controller.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/TagScrollPaneView.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/settings/InferenceSettingsView.java

* Adds null-checks for textfield commit-events.
Fixes #109.

Add null checks for textfield texts

---

src/main/java/com/github/mfl28/boundingboxeditor/ui/BoundingPolygonDrawer.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/EditorImagePaneView.java
src/test/java/com/github/mfl28/boundingboxeditor/BoundingBoxEditorTestBase.java
src/test/java/com/github/mfl28/boundingboxeditor/ui/BoundingBoxDrawingTests.java
src/test/java/com/github/mfl28/boundingboxeditor/ui/BoundingPolygonDrawingTests.java

* Sets bounding shape group mouse-transparent whenever shape drawing is initialized and resets it on drawing-finalization. This presents bounding shapes from intercepting mouse events while drawing is in progress.
* Adds mouse-transparency checks to bounding shape drawing tests.
Fixes #111.

Fix shape group mouse-transparency when drawing

---

build.gradle
src/main/java/com/github/mfl28/boundingboxeditor/controller/Controller.java
src/main/java/com/github/mfl28/boundingboxeditor/model/io/CSVSaveStrategy.java
src/main/java/com/github/mfl28/boundingboxeditor/model/io/ImageAnnotationSaveStrategy.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/MenuBarView.java
src/main/java/module-info.java
src/test/java/com/github/mfl28/boundingboxeditor/model/io/CSVSaveStrategyTest.java

While I was following [this guide](https://apple.github.io/turicreate/docs/userguide/object_detection/data-preparation.html) I needed BoundingBoxEditor to export the annotations to a CSV file. As the format is pretty specific, I'm not sure if it may be a good addition for this project. But maybe it can be extended to be more flexible in the future. The exporter can only export Rectangle annotations.
What do you think, can this be merged?
I introduced two new dependencies: OpenCSV for writing the CSV file and Jimfs for the unit tests.

CSV export strategy for Rectangle annotations

---

.github/workflows/codeql.yml
.github/workflows/workflow.yml

* Upgrades deprecated Github actions.
Closes #131.

Upgrade Github actions

---

.gitattributes
build.gradle
src/main/java/com/github/mfl28/boundingboxeditor/controller/Controller.java
src/main/java/com/github/mfl28/boundingboxeditor/model/io/CSVLoadStrategy.java
src/main/java/com/github/mfl28/boundingboxeditor/model/io/CSVSaveStrategy.java
src/main/java/com/github/mfl28/boundingboxeditor/model/io/ImageAnnotationLoadStrategy.java
src/main/java/com/github/mfl28/boundingboxeditor/model/io/ImageAnnotationSaveStrategy.java
src/main/java/com/github/mfl28/boundingboxeditor/model/io/data/CSVRow.java
src/main/java/com/github/mfl28/boundingboxeditor/model/io/restclients/BoundingBoxPredictionEntry.java
src/main/java/com/github/mfl28/boundingboxeditor/model/io/restclients/ModelEntry.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/MenuBarView.java
src/main/java/com/github/mfl28/boundingboxeditor/utils/MathUtils.java
src/main/java/module-info.java
src/test/java/com/github/mfl28/boundingboxeditor/BoundingBoxEditorTestBase.java
src/test/java/com/github/mfl28/boundingboxeditor/controller/ControllerTests.java
src/test/java/com/github/mfl28/boundingboxeditor/model/io/CSVSaveStrategyTest.java
src/test/java/com/github/mfl28/boundingboxeditor/ui/BoundingPolygonDrawingTests.java
src/test/java/com/github/mfl28/boundingboxeditor/ui/ImageFolderOpenedBasicTests.java
src/test/java/com/github/mfl28/boundingboxeditor/ui/ObjectTreeTests.java
src/test/resources/testannotations/csv/reference/annotations.csv

* Adds CSV tensorflow format as supported annotation import format.
* Switches from Opencsv to Jackson CSV databind as the former weirdly capitalizes the field-names (with no simple option to turn this off).
* Adds unit tests.
Closes #146 .

Add CSV import strategy
