mfl28/BoundingBoxEditor

build.gradle

* Upgrades JavaFX to version 17.
* Updates dependencies.
Closes #4 .

Upgrade to JavaFX 17, update dependencies.

---

.github/workflows/workflow.yml
Dockerfile
build.gradle

* Use Java 17, upgrade Github actions.
Closes #14 .

Use Java 17, upgrade Github actions

---

.github/workflows/workflow.yml

Upgrade CI macos-environment

---

build.gradle
src/test/java/com/github/mfl28/boundingboxeditor/ui/ObjectTreeTests.java

* Upgrade to JavaFX 19.
* Update unit test (including combox-subitem selection).
Closes #28 .

Upgrade to JavaFX 19

---

build.gradle

Bump version to 2.4.0

---

README.md

Update README for v2.4.0 release

---

build.gradle

Bump version to 2.5.0

---

chocolatey/boundingboxeditor.nuspec
chocolatey/tools/chocolateyinstall.ps1

Update chocolatey data for v2.5.0

---

src/main/java/com/github/mfl28/boundingboxeditor/BoundingBoxEditorApp.java
src/main/java/com/github/mfl28/boundingboxeditor/controller/Controller.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/MainView.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/MenuBarView.java
src/test/java/com/github/mfl28/boundingboxeditor/BoundingBoxEditorTestBase.java
src/test/java/com/github/mfl28/boundingboxeditor/controller/ControllerTests.java
src/test/java/com/github/mfl28/boundingboxeditor/ui/NoImageFolderOpenedBasicTests.java

* Adds `Help` menubar item with sub-menus that link to the documentation and open an about dialog.
* Adds the program version to the app window title.
* Updates and extends unit tests.
Closes #58 .

Add help menu and program version info

---

build.gradle
src/main/java/com/github/mfl28/boundingboxeditor/controller/Controller.java

Bump version to 2.5.1

---

chocolatey/boundingboxeditor.nuspec
chocolatey/tools/chocolateyinstall.ps1

Update chocolatey files for v2.5.1

---

src/main/java/com/github/mfl28/boundingboxeditor/controller/Controller.java

Filter out hidden files when loading images

---

build.gradle

Bump version to 2.6.0

---

src/main/java/com/github/mfl28/boundingboxeditor/controller/Controller.java

Update in-app version to 2.6.0

---

chocolatey/boundingboxeditor.nuspec
chocolatey/tools/chocolateyinstall.ps1

Update chocolatey for v2.6.0

---

.github/workflows/workflow.yml

Improve CI Gradle caching, improve release changelogs

---

build.gradle
src/main/java/com/github/mfl28/boundingboxeditor/controller/Controller.java
src/main/java/com/github/mfl28/boundingboxeditor/ui/BoundingPolygonDrawer.java
src/test/java/com/github/mfl28/boundingboxeditor/controller/AnnotationTests.java

* Bumps app version to 2.7.0.
* Fixes 2 minor code smells.
Closes #113.

Bump app version to 2.7.0

---

chocolatey/boundingboxeditor.nuspec
chocolatey/tools/chocolateyinstall.ps1

Update chocolatey files for v2.7.0

---

.github/workflows/sonar.yml
.github/workflows/workflow.yml

* Enables sonarlint on pull requests.
Closes #126.

Enable sonarlint on pull requests

---

build.gradle

Upgrade javafx version

---

build.gradle
src/main/java/com/github/mfl28/boundingboxeditor/model/io/CSVSaveStrategy.java
src/test/java/com/github/mfl28/boundingboxeditor/model/io/CSVSaveStrategyTest.java

Switch to tensorflow CSV format

---

build.gradle
src/main/java/com/github/mfl28/boundingboxeditor/controller/Controller.java

Bump version 2.8.0

---

chocolatey/boundingboxeditor.nuspec
chocolatey/tools/chocolateyinstall.ps1

Update chocolatey files for v2.8.0.

---

.github/workflows/workflow.yml
build.gradle

Re-add sonar analysis to CI.

---

.github/workflows/codeql.yml
.github/workflows/workflow.yml

Upgrade github action
